---
title: "Teaching Statements"
hidden-title: "Teaching Statements"
toc: true

---

<style>
h1.title {
    display: none;
}
</style>

::: {.title-styled}
<h1>{{< meta hidden-title >}}</h1>
:::

<hr class="title-divider">

## Teaching Philosophy

My teaching philosophy is driven by the belief that learning is a collaborative and interactive process. My research revolves around the remarkable role of interaction in language learning, and I see this mirrored in the classrooms of the most impactful and inspiring teachers I have known. These teachers emphasized three essential pieces of any culture of learning: learning how to learn, approaching information openly and critically, and making connections to integrate knowledge. I bring these same priorities to my teaching approach.

#### Learning how to learn

I believe both lecture and seminar classes can be shaped into interactive opportunities for students to put general reasoning skills into practice, so that learning develops as an active skill. I create a low-stakes environment where students are emboldened to share their “hot takes” and speak up when things don’t make sense. I encourage admission of ignorance as a chance to learn something new, and maintain a conversational tone where students, in their words, “never feel dumb.” It is my responsibility as an instructor to embody the attitudes I wish to promote, which means allowing my own ignorance to serve as a learning opportunity. For instance, when leading a discussion for Introduction to Human Development, I was unable to answer a student’s questions about experimental protocols for non-human primate studies. We talked about the scope of research domains and how I might go about finding an answer to something far from my area of expertise. As a class, we turned fuzzy ideas into two specific questions and went through the process of accessing library resources to find answers. 

Centering my classes around discussion when possible allows me to quickly identify and address students’ knowledge gaps. In the same introductory class, I noticed students mixing up anthropological and psychological approaches. I opened the floor to general questions about social science disciplines and learned that many students had never been explicitly taught several foundational concepts. For the next class I prepared a thirty-minute methods crash course with a brief lecture and group activity. One of the most meaningful moments in my time as an instructor happened two years later, when a graduating senior told me this crash course was the deciding factor for sticking with the major. I am proud that I was able to recognize missing pieces and make a lasting impact beyond my classroom for at least one student.

#### Critically approaching materials and concepts

With the goal of developing analytic reasoning, I stress to my students that being critical is not the same as being dismissive. My students should feel empowered to find weak points in the arguments they encounter but also work to find value in ideas they disagree with. For instance, in a lesson about WEIRD bias in psychology, I randomly assigned students to argue for one of two polarized views on the topic in a loosely structured and lighthearted debate. After some creative work to defend extreme positions they would not typically endorse, they came together in a large group discussion to reflect on nuances of the issue they had not previously considered and to collectively form a more balanced position on the matter.

When teaching the psychology of language, I ask students to reflect on their own language usage, positioning them as experts of their own experience. Students are eager to engage with course materials when they can imagine how it is directly reflected (or not!) in their own lives. Rather than brushing aside personal anecdotes as irrelevant to academic inquiry, I allow students to see their experience with language as a valuable tool for brainstorming, interrogating, and investing in a topic. Individual and shared experiences act as touchstones for delving into empirical work on course concepts, and written assignments allow students to practice differentiating objective and subjective evidence. Students learn to discern which kinds of evidence are appropriate in different forms of academic writing and oral presentation. 

#### Making connections and integrating knowledge

I aim to create opportunities for marginalized voices to be heard – quite literally – as not only welcome but indispensable in classroom discussions. By letting students make meaningful contributions to discussion through their own language expertise, I stress the importance of language diversity both academically and as a classroom community. Many contexts on a college campus implicitly or explicitly promote the use of a Mainstream American English academic register, muffling the voices of students who have been told their English is incorrect or found lacking. Individuals vulnerable to this kind of silencing are integral members of any complete discussion about language and interaction. As an instructor it is my responsibility to create opportunities for students to present their perspectives as necessary data for understanding the psychology of language. By underscoring the value of diverse language experience in the formal study of language, I can encourage contributions about interaction via multiple languages, dialects, and registers from students who identify with these experiences. These diverse voices are essential both for our theoretical understanding of interaction and for an inclusive classroom that fosters welcoming and productive discussion.

Recognizing individual differences in learning styles promotes student ownership of both classwork and their education more generally. One of the most common frustrations I have heard from students is feeling overwhelmed with pressure to bring “original ideas” into written assignments. In response, I highlight the value of a comparative approach to their coursework and tailor supports to individual students. For example, I offer students multiple strategies to go beyond a compare-and-contrast summary style paper, allowing comparative exercises to generate elusive original ideas. For students who struggle with rigidity, I ask them to imagine Piaget and Vygotsky getting a drink together at the end of a long day. What are they laughing about? What are they fighting about? Does the barkeeper have any words of wisdom? For students who learn more effectively with a structured exercise, I help them create a visual representation of the basic comparative framework they are familiar with as a first step toward a deeper analysis. I ask questions grounded in this visual representation to help students push farther. Where are the gaps and blank spots in the diagram? What overlap surprises you?

#### Assessment and evaluation

I prefer to evaluate student progress in two pieces. First, weekly iterative assignments provide students with ongoing opportunities to develop their critical thinking and writing skills. Frequent feedback allows for incremental improvement in a low-stakes assessment, and progressive assignments allow me to monitor understanding and growth, intervening as needed. With occasional longer written assignments, I can assess broader learning objectives like drawing connections across multiple theories, discriminating among texts, and producing cohesive written arguments. This assessment style is also advantageous for classes on methodology, where students can recognize and correct misconceptions with each step of a systematic concept, avoiding a domino effect of misunderstanding.

With any assessment, I believe students deserve evaluation that is transparent, consistent, and sufficient. It is important to me that my students recognize evaluation is never a punishment or personal judgment, but rather a tool they can leverage for their own benefit. I provide assignment rubrics outlining my expectations, providing structure for written feedback and modeling how students can improve future work. When possible, I enact standards- and specification-based grading. I believe incorporating these alternative grading schemes into my syllabus holds me accountable to myself and my students in assigning grades fairly, ensures consistency among teams of graders, and allows students to take ownership of their work. 

As I emphasize in my classroom, I believe the ability to recognize one’s shortcomings, mistakes, and ignorance is one of the most important and admirable abilities a scholar can learn. I stress that it is a skill to develop rather than a personality trait and confess that I have gone through the painful process of choosing to be vulnerable to criticism. I try to embody this message as a teacher by both modeling how to admit to and learn from mistakes and by actively soliciting student feedback about their learning and my teaching. Since incorporating regular and anonymous requests for student feedback, I have been able to adapt my classes to meet the needs of each particular group. I am grateful for students’ comments on both my syllabus and my teaching style, allowing me to design more effective lessons and to reflect on how I can do a better job promoting the diverse, inclusive, and supportive community I strive for. 

My philosophy on teaching is motivated by the kind of teacher I always admired and aspire to be: flexible, inquisitive, and approachable. It is my hope that these practices reinforce a culture of trust and accountability, enabling my students to develop a sense of ownership of their education they may carry with them going forward.


## Diversity, Equity, and Inclusion

Scholarship in the social sciences is inherently related to issues of diversity, equity, and inclusion. Researchers who make claims about how the mind works must recognize how our work is predicated on systems of marginalization and perpetuates existing inequity. It is my responsibility to promote representation and accessibility in the design and dissemination of my research and in my contact with students.

#### Equity in research practices

I work to be vigilantly mindful of my privilege and the inequities I risk tacitly endorsing in my research. I employ strategies like increasing the accessibility of presented materials with tools like written access papers and captions and representing a diverse range of racial, ethnic, dis/ability, and gender identities in presentation of my work. For example, I recognized that while the families in the parent-child interaction corpus I work with are representative of the racial diversity of Chicago, an overwhelming majority of the project’s “go-to videos” for presentations have historically featured white families. This discrepancy was especially great for examples of language use leading to positive outcomes, implicitly reinforcing the racist and untrue perception that Black children learn “incorrect” English in the home. I work together with several colleagues to maintain a shared collection of video clips reflecting the diversity of our families that researchers may draw from when disseminating our work.

I use my work to create avenues for students who are passionate about social justice to pursue their own research questions. For example, a recent mentee used my work as a foundation for her undergraduate honors thesis exploring pragmatic development in children with early brain injury. Another mentee was interested in how parents and adults can best support autistic children with language delays. Though no one at our institution was conducting research exactly in line with her questions, she persisted. We worked together to design and execute a thesis project giving her a background in nonverbal communication and early pragmatic development, allowing her to pursue her initial research questions in a Ph.D. program. I intend to use my resources as a faculty member to continue supporting undergraduates’ interests in these areas.

#### Accessibility in the classroom

I acknowledge that I have so far had limited ability to effect social change through my research. Most of my efforts to enacting practices of diversity, equity, and inclusion have taken place in the classroom. I design my classes to create an infrastructure of accessibility. I do not use one concrete set of classroom policies for all classes, and instead allow the learning objectives and course design to inform policies around late assignments, attendance, etc. Though there may be variation from course to course, each class’s syllabus presents its policies unambiguously. Additionally, the syllabus should clearly indicate avenues for students to request exceptions and accommodations; policies must not only be appropriate for the course, but for individual students as agents of their education.

I have been fortunate to teach and mentor students with highly diverse identities, backgrounds, and academic interests, helping me develop the ability to identify students struggling due to factors of marginalization. I have seen that a poorly written essay rarely indicates a student’s engagement with the material, overall efforts, or capacity for academic writing. More often it indicates the student is a non-native speaker of Mainstream American English, has graduated from an under-resourced school system, has a learning disability, or has been otherwise limited in opportunities for learning and practicing foundational writing skills.

I am committed to providing student-guided support. I must respect that my privilege will remain a barrier to understanding the lived experiences of my students. Although I continue to educate myself on how to best engage with diverse groups of students through DEI programming, I have seen that true diversity of individual identities means a true diversity of needs. I do not subscribe to a one-size-fits-all approach to accommodation. With respect to the example above, a student with dyslexia and a late-learner of English may have similar difficulties with grammatical errors but benefit from entirely different support structures. I firmly believe my students will always have the best understanding of their unique circumstances and needs.

#### Agency and accountability in the classroom

I aim to create a welcoming and inclusive space for all students. I have seen that even simple practices like addressing students by name, sharing preferred pronouns, and creating opportunities for students to speak directly with one another can show students they are valued and have a positive impact on classroom climate. I am grateful to the many psychologists, linguists, and others who maintain and contribute to shared databases of work from BIPOC authors, providing an invaluable resource for diversifying instructional materials. I work alongside my students to build an inclusive community, giving students concrete tools they can use to actively participate, like using “step up, step back” discussion guidelines, encouraging both calling out and calling in, and offering specific strategies for actively listening and contributing to discussion and offering firm, respectful disagreement. 

My role as preceptor for BA Honors students in Comparative Human Development illuminated a significant issue around students’ agency I had not previously considered. My students were passionate about social justice and eager to tackle research problems of diversity and equity. Yet there was a paradoxical barrier I had not anticipated. Students from marginalized groups wanted to do work with a direct impact on their own communities but worried their contributions would be dismissed for lacking an objective perspective. Meanwhile, students from highly privileged backgrounds felt they lacked the right to pursue research questions about identities they did not share and communities they did not belong to. From my vantage point, it was clear that these two concerns together put everyone in a position of being too objective or too subjective, leaving no one “allowed” to do this work. I encouraged students to explore where these beliefs came from. Unsurprisingly, the most effective way of helping students understand the value of their individual perspectives was to embrace the diversity of the group, facilitating an open discussion of these topics among the students. We saw some fears dispelled, other concerns validated. In the end, some students felt emboldened to pursue their interests. Other students continued to hold reservations and so adapted their research questions or methods based on the community’s feedback. This remained an ongoing and thought-provoking discussion throughout the year, as useful for me as for my students. I am committed to continuing this conversation in my future work with undergraduates and colleagues alike.

When a classroom is truly inclusive, marginalized voices are essential for achieving the aims of the course. I include the relationships between language and marginalization as an active part of my *Conversation in Context* syllabus, where units are designed to get students talking about the social and interactive consequences of language. For many students my classes may be the first time they have reflected on the languages they speak as factors defining their identities, reinforcing privilege and marginalization, and subconsciously influencing their own social judgments. Students may arrive fully prepared to relate familiar sources of bias to language, such as discussing how the enforcement of Standard/Mainstream American English in schools disadvantages Black students who speak African American [Vernacular] English in the home. I can use these foundational ideas to push students further, examining how this terminology contributes to normalization and othering as it pits “Standard American” against “African American,” offering an opportunity to reflect on who does and who does not have the privilege of being unmarked in society. From there, I can draw students’ attention to how speech and language can contribute to additional forms systematic othering, like the ageism and sexism surrounding upspeak and creaky voice or the ableism of disability interventions that prioritize speech over other kinds of communication. Students’ identities are not incidental as the class works through these challenging topics, they are integral.

I recognize that I still have much to learn from my students, colleagues, and communities in the way of actively promoting antiracist and inclusive scholarship. As a white, educated, cisgender woman, I must first and foremost commit to listen. I attempt to be gracious when faced with criticism and actively seek feedback for how to improve representation and accessibility in my work. “Inclusive instructor and researcher” is not a box for me to check off, it is – and will always be – a continuous and conscientious choice I must make.

